version: "3.8"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./html:/var/www/html
            - ./nginx:/etc/nginx/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        image: php:8.2-fpm
        volumes:
            - ./html:/var/www/html

    php-cli:
        image: php:8.2-cli
        volumes:
            - ./html:/var/www/html
